### ISSUE TITLE
jekyll build not working on Ubuntu 14.10

### ISSUE THREAD

**Issue by rubo77** [ffnord/startseite#13]
/var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>': undefined method `gracefully_require' for Jekyll::Deprecator:Class (NoMethodError)

**Comment by rubo77** [comment]
I fixed it by uninstalling the package `jekyll` and install the gem instead:

    sudo apt-get remove jekyll; sudo apt-get autoremove ; sudo gem install jekyll

**Comment by rubo77** [comment]
Added to the README in https://github.com/ffnord/startseite/commit/391694dd512fef4aaf41bac45841399c9da406a3
